project/corsi/routes.py
from flask import (
    Blueprint,
    render_template,
    redirect,
    url_for,
    request,
    flash,
    session,
    current_app,
)
from flask_login import login_required
from sqlalchemy import desc,asc
import datetime

from project.corsi.forms import CorsiForm, write_to_disk
from project.serate.forms import SerataForm
from project.serate.models import Serata
from project.corsi.models import Corso
from project.tags.models import Tag
from project.decorators import admin_required
from project import db


# Define blueprint
corsi_blueprint = Blueprint(
    "corsi", 
    __name__, 
    template_folder="templates",
    static_folder='../static'
)

'''
Lista dei corsi in ordine alfabetico
'''
@corsi_blueprint.route("/lista", methods=["GET"])
def lista():
    # Ordinamento alfabetico ascendente per titolo
    lista_corsi = Corso.query.order_by(asc(Corso.nome)).all()
    return render_template(
        'corsi_lista.html', 
        lista_corsi=lista_corsi
    )


'''
Creazione di un corso (senza serate e senza tags)
'''
@corsi_blueprint.route("/create", methods=["GET", "POST"])
@login_required
@admin_required
def create():

    form = CorsiForm()

    if form.validate_on_submit():

        name = form.name.data
        teacher = form.teacher.data
        level = form.level.data
        stato_corso = form.stato_corso.data
        description = form.description.data
        link_materiale = form.link_materiale.data

        n_course = Corso(name, teacher, level, description, "", stato_corso, link_materiale)
        db.session.add(n_course)

        form.name.data = ""
        form.description.data = ""
        form.teacher.data = ""
        form.level.data = ""
        form.stato_corso.data = ""
        form.link_materiale = ""
        
        try:
            db.session.commit()
            flash('Corso creato correttamente', 'success')
            return redirect(url_for('corsi.lista'))
        except Exception as e:
            db.session.rollback()
            flash("Errore durante la creazione del corso: %s" % str(e), 'danger')

    return render_template("corsi_create.html", form=form)


'''
Visualizzazione di un corso (con gestione serate e tags (TODO))
'''
@corsi_blueprint.route("/<int:corso_id>", methods=('GET', 'POST'))
def dettaglio_corso(corso_id):
    
    # Gestione aggiunta serate
    form = SerataForm()
    if form.validate_on_submit():

        data = form.data.data #date (not datetime!) object
        txt_time = form.txt_time.data #string formato HH:MM
        if not txt_time:
            txt_time = "00:00"
        # Converto in oggetto datetime.time per combinarlo con la data
        # in fase di creazione oggetto Serata
        data_time = datetime.datetime.strptime(txt_time, '%H:%M').time()
        nome =  form.nome.data
        descrizione = form.descrizione.data
        link_partecipazione = form.link_partecipazione.data
        link_registrazione = form.link_registrazione.data
        form_corso_id = form.select_corsi.data

        nuova_serata = Serata(
            nome, 
            descrizione, 
            datetime.datetime.combine(data,data_time), # Combino data con ore-minuti
            link_partecipazione,
            link_registrazione)
        nuova_serata.corso_id = form_corso_id
        
        # Reset dei campi della form serate
        form.data.data = ""
        form.txt_time.data = ""
        form.nome.data = ""
        form.descrizione.data = ""
        form.link_partecipazione.data = ""
        form.link_registrazione.data = ""      

        db.session.add(nuova_serata)
        try:
            db.session.commit()
            flash('Inserimento avvenuto con successo.', 'success')
        except Exception as e:
            flash("Errore durante l'inserimento della serata: %s" % str(e), 'error')
            db.session.rollback()
    # Preselezione nel form serate (comunque modificabile) del corso visualizzato
    form.select_corsi.data = corso_id
    corso = Corso.query.get_or_404(corso_id)
    return render_template('corsi_dettaglio.html', corso=corso, form=form)


'''
Cancellazione di un corso
'''
@corsi_blueprint.route("/delete/<int:id>", methods=('GET', 'POST'))
@login_required
@admin_required
def corso_delete(id):
    '''
    Delete corso
    '''
    my_course = Corso.query.filter_by(id=id).first()
    db.session.delete(my_course)
    try:
        db.session.commit()
        flash('Cancellazione avvenuta con successo.', 'success')
    except Exception as e:
        db.session.rollback()
        flash("Errore durante la cancellazione del corso: %s" % str(e), 'danger')
    return redirect(url_for('corsi.lista'))

@corsi_blueprint.route('/edit/<int:id>', methods=['GET', 'POST']) 
@login_required
@admin_required
def corso_edit(id):
    my_course = Corso.query.filter_by(id=id).first()
    form = CorsiForm()
    if form.validate_on_submit():

        my_course.nome = form.name.data
        my_course.insegnante = form.teacher.data
        my_course.livello = form.level.data
        my_course.stato_corso = form.stato_corso.data
        my_course.descrizione = form.description.data
        my_course.link_materiale = form.link_materiale.data
        # Multiselect ritorna una lista di id, ma per "tags" servono gli oggetti
        selected_tags_ids = form.multiselect_tags.data
        selected_tags = []
        for st in selected_tags_ids:
            selected_tags.append(Tag.query.filter_by(id=st).first())
        my_course.tags = selected_tags        
        db.session.add(my_course)
        db.session.commit()
        flash('Corso aggiornato con successo','success')
        return redirect(url_for('corsi.dettaglio_corso', corso_id=my_course.id))

    form.name.data = my_course.nome
    form.description.data = my_course.descrizione
    form.teacher.data = my_course.insegnante
    form.level.data = my_course.livello
    form.stato_corso.data = my_course.stato_corso
    form.link_materiale.data = my_course.link_materiale
    # Gestione tag id
    selected_tags_ids = []
    if my_course.tags:
        for t in my_course.tags:
            selected_tags_ids.append(Tag.query.filter_by(name=t.name).first().id)
    # process_data: per dare i valori di default al multiselect
    form.multiselect_tags.process_data(selected_tags_ids)
    return render_template('corso_edit.html', form=form, corso=my_course)    

project/corsi/templates/corsi_create.html
{% extends "base.html" %} {% block content %}

    <!-- Messaggi flash -->        
    <div class="container">
        {# Flashed messages #}
        {% with messages = get_flashed_messages(with_categories=true) %}
          {% if messages %}
            {% for category, message in messages %}
              <div class="alert alert-{{ category }}" role="alert">{{ message }}</div>
            {% endfor %}
          {% endif %}
        {% endwith %}
        {# End Flashed messages #}
    </div>


<div>
    <div class="container text-center">
        <br>
        <h1>Creazione nuovo corso</h1>
        <br>
        <p>I dettagli delle serate si potranno aggiungere da Gestione Serate</p>
        <br>
    </div>

    <div class="container">
        <div class="row align-items-center justify-content-center">
            <div class="col-md-4">
                <form class="form" method="POST" role="form">
                    {# This hidden_tag is a CSRF security feature. #}
                    {{ form.hidden_tag() }}

                    {#String forms#}
                    <div class="form-group">
                        <input type="text" class="form-control" id="name" name="name"
                               placeholder="Nome del corso" required>
                    </div>
                    <div class="form-group">
                        <input type="text" class="form-control" id="teacher" name="teacher"
                               placeholder="Nome dell'insegnante">
                    </div>

                    {#Selection#}
                    <div class="form-group">
                        <div class="bootstrap-select-wrapper" id="level">
                            <label for="level" >Livello del corso</label>
                            {{ form.level(class_='form-control') }}
                        </div>
                    </div>

                    {#Selection#}
                    <div class="form-group">
                        <div class="bootstrap-select-wrapper" id="stato_corso">
                            <label for="stato_corso" >Stato del corso</label>
                            {{ form.stato_corso(class_='form-control') }}
                        </div>
                    </div>

                    {#Text area#}
                    <div class="form-group">
                        <textarea id="description" name = "description" rows="3"></textarea>
                        <label for="description">Descrizione del corso</label>
                      </div>

                    {#Submit button#}
                    <div class="row align-items-center justify-content-center">
                            <button type="submit" class="btn btn-success">Crea nuovo corso</button>
                        </div>
                    </div>
                    <br>
                </form>
            </div>
        </div>
    </div>
</div>
<br>
{% endblock %}
                    

project/corsi/templates/corsi_dettaglio.html
{% extends "base.html" %} {% block content %}

    <!-- Messaggi flash -->
    <div class="alert alert-primary" role="alert">
        {% with messages = get_flashed_messages(with_categories=true) %}
          {% if messages %}
            {% for category, message in messages %}
              <div class="alert alert-{{ category }}" role="alert">{{ message }}</div>
            {% endfor %}
          {% endif %}
        {% endwith %}
      </div>
  
<div class="container text-center">
    <br>
    <h1>Programma di {{ corso.nome }} <span class="badge badge-secondary"> {{ corso.stato_corso }}</span></h1>
    <br>


    <!-- CORSO -->    
    <h2>{{ corso.descrizione }}<span class="badge badge-secondary"></span></h2>

    {% if corso.tags %}
    <h3>Tags 
        <!-- Lista tags -->
        {% for t in corso.tags %}
    <span class="badge badge-secondary">
        {{t.name}}
    </span>        
        {% endfor %} 
    </h3>
    {% endif %}

    <h4 class="display-4">Insegnante/i <span class="badge badge-success">{{corso.insegnante}}</span></h4>
    <h4 class="display-4">Livello <span class="badge badge-warning">{{corso.livello}}</span></h4>
    {% if corso.link_materiale %}
    <h4 class="display-4"><a href="{{corso.link_materiale}}">Materiale e documentazione</a></h4>
    {% endif %}

  </div>    <!--end center -->

  {% if corso.serate %}
  <h2 class="display-2"><span class="badge badge-info">Programma del corso</span></h2>
  <div class="bd-example">
  <div class="it-list-wrapper">
        <ul class="it-list">
            <!--Element-->
            {% for s in corso.serate %}
          <li>

            <!-- Link registrazione -->
            {% if s.link_registrazione %}
              <a href="{{ s.link_registrazione }}">
            {% else %}    
              <a href="#">
            {% endif %}
              
              <div class="it-right-zone">
                <span class="text">
                  {{ s.data.strftime('%d/%m/%Y %H:%M') }}
                  <em>{{ s.nome }} - {{ s.descrizione }}
                  </em>
                </span>
              
              <!-- Metadata registrazione -->
              {% if s.link_registrazione %}
                <span class="metadata">Clicca per la registrazione</span>
              {% else %}    
                <span class="metadata">Registrazione non presente</span>
              {% endif %}
  
              </div>
            </a>
          </li>
          {% endfor %}
        </ul>
    </div>          
  </div>
  {% endif %}

  {% if current_user.is_administrator() %}
  <br>
  <div class="container text-center">
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#confermaModifica">Modifica</button>      
    <button type="button" class="btn btn-danger pull-right" data-toggle="modal" data-target="#confermaCancellazione">Cancella il corso</button>
      <!-- Modal Modifica -->
      <div class="it-example-modal">
        <div class="modal" tabindex="-1" role="dialog" id="confermaModifica">
          <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Conferma operazione</h5>
                </div>
                <div class="modal-body">
                  <p>Vuoi procedere con la modifica ?</p>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-outline-primary btn-sm" type="button" data-dismiss="modal">Ritorna</button>
                    <a class="btn btn-primary btn-sm" href="{{ url_for('corsi.corso_edit', id=corso.id) }}" role="button">Conferma</a>
                </div>
              </div>
          </div>
        </div>
      </div>      

    <!-- Modal Cancellazione -->
    <div class="it-example-modal">
      <div class="modal" tabindex="-1" role="dialog" id="confermaCancellazione">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                  <h5 class="modal-title">Conferma operazione</h5>
              </div>
              <div class="modal-body">
                <p>Vuoi procedere con la cancellazione ?</p>
              </div>
              <div class="modal-footer">
                  <button class="btn btn-outline-primary btn-sm" type="button" data-dismiss="modal">Ritorna</button>
                  <a class="btn btn-danger btn-sm" href="{{ url_for('corsi.corso_delete', id=corso.id) }}" role="button">Conferma</a>
              </div>
            </div>
        </div>
      </div>
    </div>      

  </div>
  <br>



  <!--Aggiungi serate-->
  <div class="container text-center">
    <br>
    <h1>Aggiungi serata</h1>
    <br>
  </div>

    <!-- Gestione Nuova serata-->
    <!-- Form -->

    <div class="container">
      <div class="row align-items-center justify-content-center">
          <div class="col-md-4">
              <form class="form" method="POST" role="form">
                  {# This hidden_tag is a CSRF security feature. #}
                  {{ form.hidden_tag() }}

                  <div class="it-datepicker-wrapper">
                    <div class="form-group">
                      <input class="form-control it-date-datepicker" id="data" name="data" type="text" placeholder="Inserisci la data in formato gg/mm/aaaa" required>
                      <label for="data">Data della serata</label>
                    </div>
                  </div>
                  <script>
                    $(document).ready(function() {
                      $('.it-date-datepicker').datepicker({
                        inputFormat: ["dd/MM/yyyy"],
                        outputFormat: 'dd/MM/yyyy',
                      });
                  });
                  </script> 

                  <div class="it-timepicker-wrapper">
                    <div class="form-group">
                    <section class="time-spinner">
                      <div class="error_container" role="alert" aria-atomic="true"></div>
                      <fieldset>
                        <legend><span class="sr-only">Time</span></legend>
                        <div>
                          <div class="calendar-input-container">
                              <input class="form-control txtTime" id="txt_time" name="txt_time" type="text" placeholder="In formato hh:mm">
                              <button class="btn-time" id="btnTime1" aria-label="Time picker - Scadenza">
                                <svg class="icon">
                                  <use xlink:href="/static/bootstrap-italia/svg/sprite.svg#it-clock"></use>
                                </svg>
                              </button>
                              <label for="txt_time">Ora dell'appuntamento</label>
                          </div>
                        </div>
                      </fieldset>
                      <div class="spinner-control" aria-hidden="true" role="region" aria-label="Due Date Time" tabindex="-1">
                        <div class="spinner-hour spinner">
                          <input class="spinnerHour form-control" id="spinnerh" aria-label="hour" type="number" value="00" role="spinbutton" maxlength="2" aria-valuenow="00" aria-valuemax="23" aria-valuemin="0" bb-skip="3">
                          <div class="button-wrapper">
                            <button class="button-hour btnHourUp" id="iduph" aria-label="Increase Hour">
                              <span class="icon-up"></span>
                            </button>
                            <button class="button-hour btnHourDown" id="iddownh" aria-label="Decrease Hour">
                              <span class="icon-down"></span>
                            </button>
                          </div>
                        </div>
                        <div class="spinner-min spinner">
                          <input class="spinnerMin form-control" id="spinnerm" aria-label="minute" type="number" value="00" role="spinbutton" aria-valuenow="00" maxlength="2" aria-valuemax="59" aria-valuemin="00" bb-skip="10">
                          <div class="button-wrapper">
                            <button class="btnMinUp button-minute" id="idupm" aria-label="Increase Minute">
                              <span class="icon-up"></span>
                            </button>
                            <button class="btnMinDown button-minute" id="iddownm" aria-label="Decrease Minute">
                              <span class="icon-down"></span>
                            </button>
                          </div>
                        </div>
                      </div>
                    </section>
                  </div>
                  </div>

                  <div class="form-group">
                      <input type="text" class="form-control" id="nome" name="nome"
                             placeholder="Titolo della serata" required>
                  </div>

                  <div class="form-group">
                    <input type="text" class="form-control" id="descrizione" name="descrizione"
                           placeholder="Descrizione della serata" required>
                  </div>

                  <div class="form-group">
                    <div class="bootstrap-select-wrapper" id="select_corsi" name="select_corsi">
                      <label for="select_corsi" >Corso collegato</label>
                      {{ form.select_corsi(class_='form-control') }}
                  </div>

                  <div class="form-group">
                    <input type="text" class="form-control" id="link_partecipazione" name="link_partecipazione"
                           placeholder="Link accesso">
                  </div>

                  <div class="form-group">
                    <input type="text" class="form-control" id="link_registrazione" name="link_registrazione"
                           placeholder="Link registrazione">
                  </div>


                  {#Submit button#}
                  <div class="row align-items-center justify-content-center">
                      <button type="submit" class="btn btn-success">Aggiungi una serata</button>
                  </div>
              </div>
          </div>
    </div>


    <br>



  {% endif %}
  
{% endblock %}

project/corsi/templates/corsi_lista.html
{% extends "base.html" %} 
{% block content %}

    <!-- Messaggi flash -->        
    <div class="container">
      {# Flashed messages #}
      {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
          {% for category, message in messages %}
            <div class="alert alert-{{ category }}" role="alert">{{ message }}</div>
          {% endfor %}
        {% endif %}
      {% endwith %}
      {# End Flashed messages #}
    </div>        


<div class="container text-center">
    <br>
    <h1>Lista corsi</h1>
    <br>
</div>

<!--Lista corsi in formato CARD -->
<div class="container align-center">
<div class="row">
    {% for c in lista_corsi %}
    <div class="col-12 col-lg-8">
      <div class="card-wrapper">
      
      <div class="card card-bg">
        <div class="card-body">
          <div class="head-tags">
            <!-- Lista tags -->
            {% for t in c.tags %}
            <a class="card-tag" href="/tags/{{ t.id }}">
                  {{t.name}}
            </a>
            {% endfor %}              
            <span class="data">{{ c.livello }}</span>
          </div>
          <h5 class="card-title">{{ c.nome }} <span class="badge badge-secondary"> {{ c.stato_corso }}</span></h5>
          <p class="card-text">{{ c.descrizione }}</p>
          <div class="it-card-footer">
            <span class="card-signature">di {{c.insegnante}}</span>
            <a href="/corsi/{{ c.id }}"><button class="btn btn-outline-primary btn-sm" >Dettagli</button></a>
          </div>
        </div>
      </div>
    </div>
  </div>

  <br>
   {% endfor %}
</div>
</div>


{% endblock %}

project/corsi/templates/corso_edit.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block content %}

<!-- Messaggi flash -->
<div class="container">
    {# Flashed messages #}
    {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
        {% for category, message in messages %}
          <div class="alert alert-{{ category }}" role="alert">{{ message }}</div>
        {% endfor %}
      {% endif %}
    {% endwith %}
    {# End Flashed messages #}
</div>

<div class="container text-center">
    <br>
    <h1>Aggiornamento corso {{ corso.nome }}</h1>
    <br>
</div>

<div class="container">
    <div class="row align-items-center justify-content-center">
  
<div class="col-md-4">
    {{ wtf.quick_form(form, novalidate=True, button_map={'submit':'success'}) }}
</div>

</div>
</div>

{% endblock %}