project/utenti/routes.py
from flask import (
    Blueprint,
    render_template,
    redirect,
    url_for,
    request,
    flash,
    session,
    current_app,
)
from flask_login import (
    login_user, 
    logout_user, 
    login_required,
    current_user,
)
#Per le email
from project.email import send_email

#from project.utenti.forms import TagForm
from project.utenti.models import Utente
from project.ruoli.models import Ruolo
from project.blog.models import Post
from project import db
from project.decorators import admin_required

from sqlalchemy import desc,asc

from project.utenti.forms import (
    EditProfileForm,
    EditProfileAdminForm,
)

# Define blueprint
utenti_blueprint = Blueprint(
    "utenti", 
     __name__, 
    template_folder="templates", 
    static_folder='../static'
)



'''
ROUTES per la gestione dei PROFILI
'''
@utenti_blueprint.route('/<username>') 
def user(username):    
    u = Utente.query.filter_by(username=username).first_or_404()
    page = request.args.get('page', 1, type=int)
    pagination = u.posts.order_by(Post.timestamp.desc()).paginate(
        page, per_page=current_app.config['PBG_POSTS_PER_PAGE'],
        error_out=False)
    posts = pagination.items
    return render_template('user.html', user=u, posts=posts,
                           pagination=pagination)

@utenti_blueprint.route('/edit-profile', methods=['GET', 'POST']) 
@login_required 
def edit_profile():    
    form = EditProfileForm()
    if form.validate_on_submit():
        current_user.name = form.name.data
        current_user.location = form.location.data
        current_user.about_me = form.about_me.data
        db.session.add(current_user._get_current_object())
        db.session.commit()
        flash('Profilo aggiornato con successo','success')
        return redirect(url_for('utenti.user', username=current_user.username))
    form.name.data = current_user.name
    form.location.data = current_user.location    
    form.about_me.data = current_user.about_me
    return render_template('edit_profile.html', form=form)

@utenti_blueprint.route('/edit-profile/<int:id>', methods=['GET', 'POST'])
@login_required
@admin_required
def edit_profile_admin(id):
    user = Utente.query.get_or_404(id)
    form = EditProfileAdminForm(user=user)
    if form.validate_on_submit():
        user.email = form.email.data
        user.username = form.username.data
        user.confirmed = form.confirmed.data
        user.ruolo = Ruolo.query.get(form.role.data)
        user.name = form.name.data
        user.location = form.location.data
        user.about_me = form.about_me.data
        db.session.add(user)
        db.session.commit()
        flash('Profilo aggiornato','success')
        return redirect(url_for('utenti.user', username=user.username))
    form.email.data = user.email
    form.username.data = user.username
    form.confirmed.data = user.confirmed
    form.role.data = user.role_id
    form.name.data = user.name
    form.location.data = user.location
    form.about_me.data = user.about_me
    return render_template('edit_profile.html', form=form, user=user)

'''
Lista utenti
'''
@utenti_blueprint.route('/lista', methods=['GET', 'POST'])
@login_required
def lista():
    # Lista utenti in ordine alfabetico
    lista_utenti = Utente.query.order_by(asc(Utente.username)).all()
    return render_template(
        'utenti_lista.html', 
        lista_utenti=lista_utenti
    )

'''
Cancellazione utenti
'''
@utenti_blueprint.route("/delete/<int:id>", methods=('GET', 'POST'))
@login_required
@admin_required
def utente_delete(id):
    my_user = Utente.query.filter_by(id=id).first()
    try:        
        db.session.delete(my_user)
        db.session.commit()
        flash('Cancellazione avvenuta con successo.', 'success')
    except Exception as e:
        db.session.rollback()
        flash("Errore durante la cancellazione utente: %s" % str(e), 'danger')
    return redirect(url_for('utenti.lista'))

project/utenti/templates/edit_profile.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block content %}

<!-- Messaggi flash -->
<div class="container">
    {# Flashed messages #}
    {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
        {% for category, message in messages %}
          <div class="alert alert-{{ category }}" role="alert">{{ message }}</div>
        {% endfor %}
      {% endif %}
    {% endwith %}
    {# End Flashed messages #}
</div>

<div class="container text-center">
    <br>
    <h1>Aggiornamento profilo di {{ current_user.username }}</h1>
    <br>
</div>

<div class="container">
    <div class="row align-items-center justify-content-center">
  
<div class="col-md-4">
    {{ wtf.quick_form(form, novalidate=True, button_map={'submit':'success'}) }}
</div>

</div>
</div>

{% endblock %}

project/utenti/templates/user.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block content %}

<!-- Messaggi flash -->
<div class="container">
  {# Flashed messages #}
  {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
      {% for category, message in messages %}
        <div class="alert alert-{{ category }}" role="alert">{{ message }}</div>
      {% endfor %}
    {% endif %}
  {% endwith %}
  {# End Flashed messages #}
</div>

<div class="container">
  <div class="row align-items-center justify-content-center">

<div class="page-header">
  <img class="img-rounded profile-thumbnail" src="{{ user.gravatar(size=256) }}">
  <div class="profile-header">
      <h1>{{ user.username }}</h1>
      {% if user.name or user.location %}
      <p>
          {% if user.name %}{{ user.name }}<br>{% endif %}
          {% if user.location %}
              da <a href="http://maps.google.com/?q={{ user.location }}">{{ user.location }}</a><br>
          {% endif %}
      </p>
      {% endif %}
      {% if current_user.is_administrator() %}
      <p><a href="mailto:{{ user.email }}">{{ user.email }}</a></p>
      {% endif %}
      {% if user.about_me %}<p>{{ user.about_me }}</p>{% endif %}
      <p>Iscritto dal: {{ moment(user.member_since).format("DD/MM/YYYY") }}. Ultima visita: {{ moment(user.last_seen).fromNow() }}.</p>
      <p>
          {% if user == current_user %}
          <a class="btn btn-success" href="{{ url_for('utenti.edit_profile') }}">Aggiorna profilo</a>
          {% endif %}
          {% if current_user.is_administrator() %}
          <a class="btn btn-danger" href="{{ url_for('utenti.edit_profile_admin', id=user.id) }}">Aggiorna profilo [Admin]</a>
          {% endif %}
      </p>
  </div>
</div>
<br>
</div>
<h3>Posts by {{ user.username }}</h3>
{% include '_posts.html' %}

</div>
{% endblock %}

project/utenti/templates/utenti_lista.html
{% extends "base.html" %} 
{% block content %}

    <!-- Messaggi flash -->        
    <div class="container">
      {# Flashed messages #}
      {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
          {% for category, message in messages %}
            <div class="alert alert-{{ category }}" role="alert">{{ message }}</div>
          {% endfor %}
        {% endif %}
      {% endwith %}
      {# End Flashed messages #}
    </div>        


<div class="container text-center">
    <br>
    <h1>Lista Utenti</h1>
    <br>
</div>

<table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">Utente</th>
        <th scope="col">Email - Nome</th>
        <th scope="col">Conferma</th>
        <th scope="col">Dove vive</th>
        <th scope="col">Ruolo</th>
        {% if current_user.is_administrator() %}
        <th scope="col">Azioni</th>
        {% endif %}
      </tr>
    </thead>
      <tbody>
    {% for u in lista_utenti %}

      <tr>
        <th scope="row">
            <a href="{{ url_for('utenti.user', username=u.username) }}">
                <div class="it-right-zone">
                    <span class="avatar size-lg"><img src="{{ u.gravatar(size=64) }}" alt="{{ u.username }}"></span>
                    <span class="text">{{ u.username }}</span>
                </div>
            </a>
        </th>
        <td>{{ u.email }} - {{ u.name }}</td>
        <td>
            {% if u.confirmed %}
              Confermato
            {% else %}
              Non confermato
            {% endif %}
        </td>
        <td>
          {% if u.location %}
            <a href="http://maps.google.com/?q={{ u.location }}">{{ u.location }}</a>
          {% else %}
            Non disponibile
          {% endif %}
        </td>
        <!--Ruolo-->
        <td>
          {{ u.ruolo }}
        </td>
        {% if current_user.is_administrator() %}
        <!--Azioni-->
        <td>
          <a class="btn btn-primary pull-right" href="{{ url_for('utenti.edit_profile_admin', id=u.id) }}">Aggiorna profilo</a>
          <!--Modal check -->
          <button type="button" class="btn btn-danger pull-right" data-toggle="modal" data-target="#confermaCancellazione{{u.id}}">Cancella</button>
          <!-- Modal Cancellazione -->
          <div class="it-example-modal">
            <div class="modal" tabindex="-1" role="dialog" id="confermaCancellazione{{u.id}}">
              <div class="modal-dialog" role="document">
                  <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">Conferma operazione</h5>
                    </div>
                    <div class="modal-body">
                      <p>Vuoi procedere con la cancellazione dell'utente {{u.username}} ?</p>
                    </div>
                    <div class="modal-footer">
                        <button class="btn btn-outline-primary btn-sm" type="button" data-dismiss="modal">Ritorna</button>
                        <a class="btn btn-danger btn-sm" href="{{ url_for('utenti.utente_delete', id=u.id) }}" role="button">Conferma</a>
                    </div>
                  </div>
              </div>
            </div>
          </div>        
        
        </td>
        {% endif %}
      </tr>
      {% endfor -%}
    </tbody>
  </table>

  {% endblock %}