project/tags/models.py
from project import db
from sqlalchemy import desc,asc

class Tag(db.Model):

    __tablename__ = "tag"

    id = db.Column(db.Integer(), primary_key=True)
    name = db.Column(db.String(255), unique=True, nullable=False)

    def __init__(self, name):
        self.name = name

    def __repr__(self):
        return "<Tag '{}'>".format(self.name)

    # Per la gestione API - Serializing Resources to JSON
    def to_json(self):
        json_tag = {
            'tag': self.name
        }
        return json_tag
    
    '''
    Utile per il popolamento dei dati e per i test
    '''
    @staticmethod
    def insert_test_tags():
        tags = [ 
            "Python", "Flask", "Pygame",
            "SqlAlchemy", "Web Development", "Graphics",
            "NumPy", "Pandas", "Django"
        ]
        for name_tag in tags:
            tag = Tag.query.filter_by(name=name_tag).first()
            if tag is None:
                tag = Tag(name=name_tag)
            db.session.add(tag)
        db.session.commit()

    @staticmethod
    def all_tags_selection():
        lista_tags = Tag.query.order_by(asc(Tag.name)).all()
        selection = []
        for t in lista_tags:
            selection.append((t,t))
        return selection

project/tags/forms.py
from flask_wtf import FlaskForm

from wtforms import (
    Form,
    validators,
    StringField,
)
from wtforms.validators import DataRequired, Length

'''
Tag Form
'''
class TagForm(FlaskForm):
    name = StringField(u'Titolo tag', validators=[Length(min=-1, max=255, message='Massimo 255 caratteri')])

project/tags/routes.py
from flask import (
    Blueprint,
    render_template,
    redirect,
    url_for,
    request,
    flash,
    session,
    current_app,
)
from flask_login import login_required

from project.tags.forms import TagForm
from project.tags.models import Tag
from project import db
from project.decorators import admin_required

from sqlalchemy import desc,asc

# Define blueprint
tags_blueprint = Blueprint(
    "tags", 
     __name__, 
    template_folder="templates", 
    static_folder='../static'
)    

'''
Lista dei tags con la possibilità di creazione di nuovo tag
'''
@tags_blueprint.route("/", methods=('GET', 'POST'))
@login_required
def tags():
    # Ordinamento alfabetico ascendente per "name"
    lista_tags = Tag.query.order_by(asc(Tag.name)).all()
    '''
    Crea nuovo tag
    '''
    form = TagForm()
    if form.validate_on_submit():
        tag_name = form.name.data
        n_tag = Tag(tag_name)
        db.session.add(n_tag)
        form.name.data = ""
        try:
            db.session.commit()
            flash('Tag creato correttamente', 'success')
            return redirect(url_for('tags.tags'))
        except Exception as e:
            db.session.rollback()
            flash("Errore durante la creazione del tag: %s" % str(e), 'danger')

    return render_template('tags_lista.html', form=form, lista_tags=lista_tags)

'''
Cancellazione tag
'''
@tags_blueprint.route("/delete/<int:id>", methods=('GET', 'POST'))
@login_required
@admin_required
def tag_delete(id):
    '''
    Delete tag
    '''
    my_tag = Tag.query.filter_by(id=id).first()
    db.session.delete(my_tag)
    try:
        db.session.commit()
        flash('Cancellazione avvenuta con successo.', 'success')
    except Exception as e:
        db.session.rollback()
        flash("Errore durante la cancellazione del tag: %s" % str(e), 'danger')
    return redirect(url_for('tags.tags'))

'''
Modifica tag by id
'''
@tags_blueprint.route("/<id>", methods=('GET', 'POST'))
@login_required
@admin_required
def edit_tag(id):
    '''
    Edit tag
    :param id: Id from tag
    '''
    my_tag = Tag.query.filter_by(id=id).first()
    form = TagForm(obj=my_tag)
    if form.validate_on_submit():
        form.populate_obj(my_tag)
        db.session.add(my_tag)
        try:
            db.session.commit()
            flash('Aggiornamento avvenuto con successo', 'success')
        except Exception as e:
            db.session.rollback()
            flash("Errore durante l'aggiornamento del tag: %s" % str(e), 'danger')
    return render_template(
        '/tags_edit.html',
        form=form,tag=my_tag)

project/tags/templates/lista.html
{% extends "base.html" %} {% block content %}

    <!-- Messaggi flash -->
    <div class="container">
      {# Flashed messages #}
      {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
          {% for category, message in messages %}
            <div class="alert alert-{{ category }}" role="alert">{{ message }}</div>
          {% endfor %}
        {% endif %}
      {% endwith %}
      {# End Flashed messages #}
  </div>        


<div class="container text-center">
    <br>
    <h1>Lista tags</h1>
    <br>
</div>

    <!-- Lista tags -->    
    <h1 class="display-1">
      {% for t in lista_tags %}
      <div>
      <span class="badge badge-secondary">{{t.name}}</span>
      <!-- Edit e cancellazione tag ammessi solo al profilo amministratore -->
      {% if current_user.is_administrator() %}
      <a class="btn btn-primary pull-right" href="{{ url_for('tags.edit_tag', id=t.id) }}">Edit</a>
      <a class="btn btn-danger pull-right" href="{{ url_for('tags.tag_delete', id=t.id) }}">Cancella</a>
      {% endif %}
      </div>
      {% endfor %}
    </h1>

    {% if current_user.is_administrator() %}
    <!-- Form per la creazione di nuovi tag -->        
        <div class="container text-center">
          <br>
          <h1>Nuovo tag</h1>
          <br>
        </div>

        {% block body %}
        <div class="container">
          <div class="row align-items-center justify-content-center">
            <div class="col-md-4">
                  <form class="form" method="POST" role="form">
                      {# This hidden_tag is a CSRF security feature. #}
                      {{ form.hidden_tag() }}
                      {#String forms#}
                      <div class="form-group">
                          <input type="text" class="form-control" id="name" name="name"
                                 placeholder="Nome del tag" required>
                      </div>
                      {#Submit button#}
                      <div class="row align-items-center justify-content-center">
                        <button type="submit" class="btn btn-success">Crea nuovo tag</button>
                      </div>
                  </form>
            </div>
          </div>
        </div>
        {% endblock %}
    {% endif %}

    {% endblock %}

project/tags/templates/tags_edit.html
{% extends "base.html" %} {% block content %}

    <!-- Messaggi flash -->        
    <div class="container">
        {# Flashed messages #}
        {% with messages = get_flashed_messages(with_categories=true) %}
          {% if messages %}
            {% for category, message in messages %}
              <div class="alert alert-{{ category }}" role="alert">{{ message }}</div>
            {% endfor %}
          {% endif %}
        {% endwith %}
        {# End Flashed messages #}
    </div>        

    <!-- Gestione Edit -->
    <div class="container text-center">
      <br>
      <h1>Modifica tag {{ tag.name }}</h1>
      <br>
    </div>

    <div class="container">
        <div class="row align-items-center justify-content-center">
            <div class="col-md-4">
                <form class="form" method="POST" role="form">
                    {# This hidden_tag is a CSRF security feature. #}
                    {{ form.hidden_tag() }}
                    {#String forms#}
                    <div class="form-group">
                        <input type="text" class="form-control" id="name" name="name"
                               placeholder="Nuovo nome del tag" required>
                    </div>
                    {#Submit button#}
                    <div class="row align-items-center justify-content-center">
                        <button type="submit" class="btn btn-success">Aggiorna</button>
                    </div>
                </div>
            </div>
    </div>

  <!-- Link di navigazione -->
  <div class="container text-center">
    <div class="link-list-wrapper">
      <ul class="link-list">
        <li><a class="list-item" href="{{ url_for('tags.tags') }}"><span>Lista tags</span></a></li>
        <li><a class="list-item" href="{{ url_for('corsi.lista') }}"><span>Lista corsi</span></a></li>
      </ul>
    </div>
  </div>    

{% endblock %}

project/tags/templates/tags_lista.html
{% extends "base.html" %} {% block content %}

    <!-- Messaggi flash -->
    <div class="container">
      {# Flashed messages #}
      {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
          {% for category, message in messages %}
            <div class="alert alert-{{ category }}" role="alert">{{ message }}</div>
          {% endfor %}
        {% endif %}
      {% endwith %}
      {# End Flashed messages #}
  </div>        


<div class="container text-center">
    <br>
    <h1>Lista tags</h1>
    <br>
</div>

    <!-- Lista tags -->    
    <h1 class="display-1">
      {% for t in lista_tags %}
      <div>
      <span class="badge badge-secondary">{{t.name}}</span>
      <!-- Edit e cancellazione tag ammessi solo al profilo amministratore -->
      {% if current_user.is_administrator() %}
      <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#confermaModifica{{t.id}}">Modifica</button>
      <button type="button" class="btn btn-danger pull-right" data-toggle="modal" data-target="#confermaCancellazione{{t.id}}">Cancella</button>
      <!-- Modal Modifica -->
      <div class="it-example-modal">
        <div class="modal" tabindex="-1" role="dialog" id="confermaModifica{{t.id}}">
          <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Conferma operazione</h5>
                </div>
                <div class="modal-body">
                  <p>Vuoi procedere con la modifica ?</p>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-outline-primary btn-sm" type="button" data-dismiss="modal">Ritorna</button>
                    <a class="btn btn-primary btn-sm" href="{{ url_for('tags.edit_tag', id=t.id) }}" role="button">Conferma</a>
                </div>
              </div>
          </div>
        </div>
      </div>      
      <!-- Modal Cancellazione -->
      <div class="it-example-modal">
        <div class="modal" tabindex="-1" role="dialog" id="confermaCancellazione{{t.id}}">
          <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Conferma operazione</h5>
                </div>
                <div class="modal-body">
                  <p>Vuoi procedere con la cancellazione ?</p>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-outline-primary btn-sm" type="button" data-dismiss="modal">Ritorna</button>
                    <a class="btn btn-danger btn-sm" href="{{ url_for('tags.tag_delete', id=t.id) }}" role="button">Conferma</a>
                </div>
              </div>
          </div>
        </div>
      </div>      
      {% endif %}
      </div>
      {% endfor %}
    </h1>


    {% if current_user.is_administrator() %}
    <!-- Form per la creazione di nuovi tag -->        
        <div class="container text-center">
          <br>
          <h1>Nuovo tag</h1>
          <br>
        </div>

        {% block body %}
        <div class="container">
          <div class="row align-items-center justify-content-center">
            <div class="col-md-4">
                  <form class="form" method="POST" role="form">
                      {# This hidden_tag is a CSRF security feature. #}
                      {{ form.hidden_tag() }}
                      {#String forms#}
                      <div class="form-group">
                          <input type="text" class="form-control" id="name" name="name"
                                 placeholder="Nome del tag" required>
                      </div>
                      {#Submit button#}
                      <div class="row align-items-center justify-content-center">
                        <button type="submit" class="btn btn-success">Crea nuovo tag</button>
                      </div>
                  </form>
            </div>
          </div>
        </div>
        {% endblock %}
    {% endif %}

    {% endblock %}