project/commenti/models.py
from project import db
from markdown import markdown
from flask import current_app, request, url_for
import bleach
from datetime import datetime
from project.exceptions import ValidationError

'''
Comment
'''
class Comment(db.Model):
    __tablename__ = 'comments'
    id = db.Column(db.Integer, primary_key=True)
    body = db.Column(db.Text)
    body_html = db.Column(db.Text)
    timestamp = db.Column(db.DateTime, index=True, default=datetime.utcnow)
    disabled = db.Column(db.Boolean)
    author_id = db.Column(db.Integer, db.ForeignKey('utenti.id'))
    post_id = db.Column(db.Integer, db.ForeignKey('posts.id'))

    @staticmethod
    def on_changed_body(target, value, oldvalue, initiator):
        allowed_tags = ['a', 'abbr', 'acronym', 'b', 'code', 'em', 'i',
                        'strong']
        target.body_html = bleach.linkify(bleach.clean(
            markdown(value, output_format='html'),
            tags=allowed_tags, strip=True))

    # Per la gestione API - Serializing Resources to JSON
    def to_json(self):
        json_comment = {
            'url': url_for('api.get_comment', id=self.id),
            'post_url': url_for('api.get_post', id=self.post_id),
            'body': self.body,
            'body_html': self.body_html,
            'timestamp': self.timestamp,
            'author_url': url_for('api.get_utente', id=self.author_id),
        }
        return json_comment
    
    # Per la gestione API - Serializing Resources from JSON
    @staticmethod
    def from_json(json_comment):
        body = json_comment.get('body')
        if body is None or body == '':
            raise ValidationError('Il commento non ha un body')
        return Comment(body=body)


db.event.listen(Comment.body, 'set', Comment.on_changed_body)

project/commenti/forms.py
from flask_wtf import FlaskForm
from wtforms import SubmitField, StringField
from wtforms.validators import DataRequired
from wtforms import ValidationError

class CommentForm(FlaskForm):
    body = StringField('Inserisci qui il tuo commento', validators=[DataRequired(message='Inserisci un testo')])
    submit = SubmitField('Conferma')

project/commenti/routes.py
from flask import Blueprint, render_template, redirect, url_for, abort, flash, request,\
    current_app, make_response
from flask_login import login_required, current_user

from project import db
from project.decorators import permission_required

from project.blog.forms import PostForm
from project.commenti.forms import CommentForm

from project.blog.models import Post
from project.commenti.models import Comment
from project.ruoli.models import Permission


# Define blueprint
commenti_blueprint = Blueprint(
    "commenti", 
     __name__, 
    template_folder="templates", 
    static_folder='../static'
)


'''
Gestione commenti da moderare
'''
@commenti_blueprint.route('/')
@login_required
@permission_required(Permission.MODERATE)
def moderate():
    page = request.args.get('page', 1, type=int)
    # Paginazione sui commenti
    pagination = Comment.query.order_by(Comment.timestamp.desc()).paginate(
        page, per_page=current_app.config['PBG_COMMENTS_PER_PAGE'],
        error_out=False)
    comments = pagination.items
    return render_template('moderate.html', comments=comments,
                           pagination=pagination, page=page)


'''
Ri-abilita commento
'''
@commenti_blueprint.route('/enable/<int:id>')
@login_required
@permission_required(Permission.MODERATE)
def moderate_enable(id):
    comment = Comment.query.get_or_404(id)
    comment.disabled = False
    db.session.add(comment)
    db.session.commit()
    return redirect(url_for('.moderate',
                            page=request.args.get('page', 1, type=int)))

'''
Disabilita commento
'''
@commenti_blueprint.route('/disable/<int:id>')
@login_required
@permission_required(Permission.MODERATE)
def moderate_disable(id):
    comment = Comment.query.get_or_404(id)
    comment.disabled = True
    db.session.add(comment)
    db.session.commit()
    return redirect(url_for('.moderate',
                            page=request.args.get('page', 1, type=int)))

project/commenti/templates/_comments.html
<ul class="comments">
    {% for comment in comments %}
    <li class="comment">
        <div class="comment-thumbnail">
            <a href="{{ url_for('utenti.user', username=comment.author.username) }}">
                <img class="img-rounded profile-thumbnail" src="{{ comment.author.gravatar(size=40) }}">
            </a>
        </div>
        <div class="comment-content">
            <div class="comment-date">{{ moment(comment.timestamp).fromNow() }}</div>
            <div class="comment-author"><a href="{{ url_for('utenti.user', username=comment.author.username) }}">{{ comment.author.username }}</a></div>
            <div class="comment-body">
                {% if comment.disabled %}
                <p><i>Questo commento è stato disabilitato da un moderatore.</i></p>
                {% endif %}
                {% if moderate or not comment.disabled %}
                    {% if comment.body_html %}
                        {{ comment.body_html | safe }}
                    {% else %}
                        {{ comment.body }}
                    {% endif %}
                {% endif %}
            </div>
            {% if moderate %}
                <br>
                {% if comment.disabled %}
                <a class="btn btn-success btn-xs" href="{{ url_for('commenti.moderate_enable', id=comment.id, page=page) }}">Abilita</a>
                {% else %}
                <a class="btn btn-danger btn-xs" href="{{ url_for('commenti.moderate_disable', id=comment.id, page=page) }}">Disabilita</a>
                {% endif %}
            {% endif %}
        </div>
    </li>
    {% endfor %}
</ul>

project/commenti/templates/moderate.html
{% extends "base.html" %}
{% import "_macros.html" as macros %}
{% block content %}

    <!-- Messaggi flash -->
    <div class="alert alert-primary" role="alert">
        {% with messages = get_flashed_messages(with_categories=true) %}
          {% if messages %}
            {% for category, message in messages %}
              <div class="alert alert-{{ category }}" role="alert">{{ message }}</div>
            {% endfor %}
          {% endif %}
        {% endwith %}
      </div>

      <div class="container text-center">
        <br>
        <h1>Moderazione commenti</h1>
        <br>
    </div>

{% set moderate = True %}
{% include '_comments.html' %}
{% if pagination %}
<div class="pagination">
    {{ macros.pagination_widget(pagination, 'commenti.moderate') }}
</div>
{% endif %}
{% endblock %}